### ISSUE TITLE
How does starlette get initialized?

### ISSUE THREAD

**Issue by vsoch** [gbozee/django-starlette#1]
Hi! I'm interested in trying this out and was very happy to find this example, but I don't see anywhere how the Starlette app folder gets integrated into the Django app. Is this something that you figured out, or am I missing the detail? Thank you!

**Comment by gbozee** [comment]
The starlette application is standalone. But makes use of django models.

**Comment by vsoch** [comment]
Thank you the clarification! I wound up using a simple approach with threads and Django alone as I have most of my Django views already, but I'll definitely give starlette a try for a future project! The app I'm working on has two modes - a single user notebook (where threads should work fine) vs. a more production deployment where I'll likely fall back to good old django_q with redis.

Thanks for your speedy response, happy holidays!
